name: Deploy to EC2
on:
  push:
    branches:
      - main
    
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Print My Name
          run: |
            echo "Subhajit Datta"
            echo "DevOps"
        - name: Current Folder
          run: |
               pwd
